# Generated by Django 2.2.1 on 2019-06-15 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0002_auto_20190529_2339'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['title']},
        ),
    ]
